<a href="https://colab.research.google.com/github/Mohanraj-E/Assignment-2/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
Z = np.zeros(10)
print(Z)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
A = np.zeros((5,5))

print("%d bytes" % (A.size * A.itemsize))

200 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
array = np.zeros(10)
array[4] = 1

print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
vector = np.arange(10,49)
print(vector,"\n")

# If 49 needs to be included the

vector1 = np.arange(10,50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48] 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
vector = np.arange(10,49)

print("Vector before reversed : ","\n",vector,"\n")
print("Vector after reversed : ","\n",vector[::-1])

Vector before reversed :  
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48] 

Vector after reversed :  
 [48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x =  np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
A = [1,2,0,0,4,0]
print("Indices of non-zero elements from [1,2,0,0,4,0] is : ","\n",np.nonzero(A))

Indices of non-zero elements from [1,2,0,0,4,0] is :  
 (array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
Imat=np.eye(3,3)
print("The 3x3 Identity Matrix is : ","\n",Imat)

The 3x3 Identity Matrix is :  
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
ran = np.random.random((3,3,3))
print("The 3x3x3 Array with Random Values","\n",ran)

The 3x3x3 Array with Random Values 
 [[[0.92216549 0.25912293 0.19976905]
  [0.23129221 0.58132105 0.11300904]
  [0.27402942 0.03719456 0.55495405]]

 [[0.26823397 0.87155735 0.62660432]
  [0.8467689  0.10049441 0.49983414]
  [0.31125423 0.03742039 0.72187084]]

 [[0.15305946 0.75833696 0.9727895 ]
  [0.78694398 0.94132765 0.58113354]
  [0.96561676 0.37882964 0.26571725]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
ran1 = np.random.random((10,10))
print("The Minimum Value is : ",ran1.min())
print("The Maximum Value is : ",ran1.max())

The Minimum Value is :  0.004645570068016247
The Maximum Value is :  0.9954645146674915


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
ran2 = np.random.random(30)
print("The mean value of the random vector of size 30 is : ",ran2.mean())

The mean value of the random vector of size 30 is :  0.4566523702307503


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1]=0
print("2d array with 1 on the border and 0 inside : ","\n",Z)

2d array with 1 on the border and 0 inside :  
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
Z = np.ones((10,10))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print("A border (filled with 0's) around an existing array : ","\n",Z)

A border (filled with 0's) around an existing array :  
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
Z = np.diag(1+np.arange(4), k = -1)

print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
Checker = np.zeros ((8,8), dtype=int)

Checker[1::2, ::2]= 1
Checker[::2, 1::2] = 1

print (Checker)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print ("In (6,7,8) shape array the index (x,y,z) of the 100th element is : ",np.unravel_index(100, (6,7,8)))

In (6,7,8) shape array the index (x,y,z) of the 100th element is :  (1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
array1= np.array([[0,1], [1,0]])
Za = np.tile(array1,(4,4))

print ("Checkerboard 8x8 matrix using the tile function : ","\n",Za)

Checkerboard 8x8 matrix using the tile function :  
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
Norm = np.random.random((5,5))
Normmax, Normmin = Norm.max(), Norm.min()
mat= (Norm-Normmin)/(Normmax-Normmin)

print ("Normalized a 5x5 random matrix is :","\n",mat)

Normalized a 5x5 random matrix is : 
 [[0.48303437 0.76818561 0.         1.         0.93848092]
 [0.26139761 0.05253568 0.49604607 0.28129776 0.00249424]
 [0.70864803 0.41973432 0.39974675 0.99565645 0.51491512]
 [0.17318114 0.80810194 0.46479606 0.04332177 0.94213923]
 [0.84623212 0.78585184 0.87810074 0.94470133 0.51156244]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)

col = input()
print(color[col])
type(color)

blue
4


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
mat1= np.dot(np.ones((5,3)), np.ones((3,2)))

print (mat1)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
arr1 = np.arange(16)

print("If 3 and 8 Not to be included : ","\n")
arr1 [(arr1 >= 3) & (arr1 <= 8)] = (-1)
print(arr1,"\n")

arr2 = np.arange(16)
print("If 3 and 8 are to be included : ","\n")
arr2 [(arr2 > 3) & (arr2 < 8)] = (-1)
print(arr2)

arr3 = np.arange(16)
print("Or According to the hint : ","\n")
arr3 [(arr3 > 3) & (arr3 <= 8)] = (-1)
print(arr3)

If 3 and 8 Not to be included :  

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10 11 12 13 14 15] 

If 3 and 8 are to be included :  

[ 0  1  2  3 -1 -1 -1 -1  8  9 10 11 12 13 14 15]
Or According to the hint :  

[ 0  1  2  3 -1 -1 -1 -1 -1  9 10 11 12 13 14 15]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

In [ ]:
print(np.sum(range(5),-1))
from numpy import *
print(np.sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(3) 
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z) # This expression is illegal

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
round = np.random.uniform(-10, +10, 10)
Rounds = np.copysign(np.ceil(np.abs(round)), round)

print(Rounds)

[-9.  5. -8. -9.  8.  3. 10. -2.  2.  9.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
A1 = np.arange(0, 20)
A2 = np.arange(15, 30)
CA = np.intersect1d(A1,A2)

print(CA)

[15 16 17 18 19]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
defaults = np.seterr(all="ignore")
Zd = np.ones(1) / 0
print(Zd)

# Back to Normal
_ = np.seterr(**defaults)

[inf]


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
#  No the expression is false

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("Yesterday : ",yesterday)
print("Today : ",today)
print("Tomorrow : ",tomorrow)

Yesterday :  2022-09-10
Today :  2022-09-11
Tomorrow :  2022-09-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
mon = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(mon)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3

print("Addision : ",np.add(A, B, out=B),"\n")
print("Division :",np.divide(A, 2, out=A),"\n")
print("Negative : ",np.negative(A, out=A),"\n")
print("Multiplication : ",np.multiply(A, B, out=A))


Addision :  [3. 3. 3.] 

Division : [0.5 0.5 0.5] 

Negative :  [-0.5 -0.5 -0.5] 

Multiplication :  [-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print(np.trunc(Z))

[5. 4. 9. 9. 3. 2. 2. 7. 3. 7.]
[5. 4. 9. 9. 3. 2. 2. 7. 3. 7.]
[5. 4. 9. 9. 3. 2. 2. 7. 3. 7.]
[5 4 9 9 3 2 2 7 3 7]
[5. 4. 9. 9. 3. 2. 2. 7. 3. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)

print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate(): 
    for x in range(10):
        yield x
        
Z = np.fromiter(generate(), dtype=float, count=-1)

print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
za = np.linspace(0,1,10,endpoint=True)[1:-1]

print(za)

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667 0.77777778 0.88888889]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
so = np.random.random(10)
so.sort()

print(so)

[0.05490308 0.20318712 0.3313406  0.37870407 0.5095514  0.52893915
 0.59107974 0.65807114 0.73116615 0.81424847]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
Z = np.arange(25)
np.add.reduce(Z)

300

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,5,10)
B = np.random.randint(0,20,10)
close = np.allclose(A,B)
equal = np.array_equal(A,B)

print(equal)
print(close)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
imm = np.zeros(10)
imm.flags.writeable = False
imm[0] = 1 # Proof

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
po = np.random.random((10,2))
X,Y = po[:,0], po[:,1]

R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)

print(R,"\n")
print(T)

[1.23028864 0.9472287  0.66399733 1.11743256 1.059402   1.27343281 0.68389214 0.31521664 0.74440833 0.91869788] 

[0.77732283 0.44207026 0.88971059 0.60781053 0.85013351 0.78324224 1.29573819 0.04865484 0.89917526 1.06529611]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
ma = np.random.random(10)
ma[ma.argmax()] = 0

print(ma)

[0.6692907  0.62054236 0.41686168 0.1236167  0.55774571 0.70528228
 0.57207466 0.16968494 0.         0.60598113]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
z = np.zeros((10, 10), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))

print(z)

[[(0.        , 0.        ) (0.11111111, 0.        ) (0.22222222, 0.        ) (0.33333333, 0.        ) (0.44444444, 0.        ) (0.55555556, 0.        ) (0.66666667, 0.        ) (0.77777778, 0.        ) (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111) (0.22222222, 0.11111111) (0.33333333, 0.11111111) (0.44444444, 0.11111111) (0.55555556, 0.11111111) (0.66666667, 0.11111111) (0.77777778, 0.11111111) (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222) (0.22222222, 0.22222222) (0.33333333, 0.22222222) (0.44444444, 0.22222222) (0.55555556, 0.22222222) (0.66666667, 0.22222222) (0.77777778, 0.22222222) (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333) (0.22222222, 0.33333333) (0.33333333, 0.33333333) (0.44444444, 0.33333333) (0.55555556, 0.33333333) (0.66666667, 0.33333333) (0.77777778, 0.33333333) (0.88888889, 0.33333333) (1.        , 0

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.random.random((10, 10))
y = np.random.random((10, 10))

c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)

print(np.linalg.det(c))

[[-5.64731150e+12  2.73189718e+14  8.04992663e+11 -1.73236324e+15 -4.62116633e+14 -7.74838799e+11 -7.06799978e+16  2.21560819e+12 -1.32329794e+13  8.89983068e+14]
 [ 1.34913804e+13 -6.73584919e+13  4.55741276e+13 -6.02626504e+13 -7.32652780e+13  1.17409916e+15  2.46128322e+12  2.42365161e+13  4.03575744e+15 -5.16059330e+15]
 [ 9.65489456e+15 -2.81377448e+13 -4.89732105e+13  7.90077226e+13 -3.50044476e+12 -2.90824188e+18 -1.02890826e+12  4.96504448e+14 -7.16582122e+16 -1.72802859e+17]
 [ 1.30771458e+14 -1.76641227e+15  1.91289788e+13 -3.64733159e+14  2.17011350e+13 -3.64382560e+14  7.44821874e+16 -2.67842587e+12 -2.27784001e+15  4.86947866e+14]
 [ 9.07942029e+14  2.24356452e+14 -3.38014314e+14  1.40955608e+13  5.99761175e+13 -8.57309108e+13 -1.51853456e+13  4.54713750e+15  5.92283353e+14  2.97713467e+12]
 [ 6.57678325e+15 -1.10099628e+15 -6.52149991e+14  1.40154514e+13  1.39184132e+13  1.21787985e+14 -1.02669897e+14  3.46844242e+13 -9.70147902e+13  4.67626220e+11]
 [-2.07560753e+13  5.0

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
print("For Integer : ")
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max,"\n")

print("For Float : ")
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps,"\n")

For Integer : 
-128
127 

-2147483648
2147483647 

-9223372036854775808
9223372036854775807 

For Float : 
-3.4028235e+38
3.4028235e+38
1.1920929e-07 

-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16 



#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=np.inf, linewidth=np.nan)
Z = np.ones((25,50))

print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
Z = np.arange(10)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()

print(Z[index])

9


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]), ('color',    [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])

print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

print(D)



[[0.         0.20029076 0.79760883 0.55001876 0.71205034 0.70529998 0.41364304 0.3489396  0.9371567  0.98129903 0.19500489 0.44195555 0.10632057 0.28648813 0.37277955 0.67691964 0.46703952 0.82944267 0.72072513 0.5270271  0.6278893  0.6166937  0.65337675 0.6554364  0.64262505 0.80899287 0.62197497 0.693693   0.68001819 0.35087048 0.83926583 0.29008226 0.48440908 0.07068809 1.0288964  0.3527656  0.52753337 0.59661837 0.10211135 0.37132612 0.58560753 0.36277627 0.64303281 0.54495593 0.35816815 0.77521769 0.52337074 0.54163019 0.78154138 0.10546117 0.60336758 0.31147479 0.77156687 0.41571777 0.632387   0.92277191 0.60320361 0.6804021  0.20554113 0.0713485  0.4301705  0.2385152  0.24496395 0.63068144 0.84852541 0.69720113 0.95965937 0.60909837 0.19718791 0.57835938 0.2306559  0.34507349 0.34883313 0.29124554 0.49983839 0.51857696 0.44036498 0.90530658 0.10928192 0.25062288 0.66778317 0.91381032 0.22193873 0.45610014 0.6590206  0.63229438 0.63852001 0.30466577 0.4619607  0.79980197 0.078745

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

Z = np.genfromtxt(s, delimiter=",", dtype=np.int)

print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)

print("numerate : ")
for index, value in np.ndenumerate(Z):
    print(index, value)


print("\n","index : ")  
for index in np.ndindex(Z.shape):
    print(index, Z[index])

numerate : 
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

 index : 
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0

G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )

print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818 0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.5461

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))

np.put(Z, np.random.choice(range(n*n), p, replace=False),1)

print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
X = np.random.rand(10, 20)

Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.3138326  -0.17303491  0.4415264   0.43986559  0.48901378  0.1326427  -0.2050438  -0.01407909  0.3220103  -0.03289422  0.42868521 -0.35282983 -0.44573909  0.17308151 -0.27340876 -0.29130042 -0.1966591  -0.32506649 -0.13025534  0.32731815]
 [-0.23292527 -0.27831623 -0.32237274  0.14746905  0.4248699   0.01074495  0.17231209 -0.27411727  0.04070713  0.07947269 -0.43382496  0.10201991 -0.19872287 -0.02132741  0.32606951  0.43007235 -0.2370184  -0.1388595   0.46738225 -0.06363518]
 [-0.38705631  0.28991502  0.28448874  0.17061765 -0.19575021 -0.19308814 -0.33940686  0.54943255 -0.16306908 -0.26185389 -0.17242196  0.14139632  0.21336841  0.15027041  0.04646558 -0.26229961 -0.21361629 -0.0816271   0.21806609  0.20616866]
 [-0.22863967  0.26183623  0.24009482  0.2471272  -0.08794718 -0.24911009  0.13009562 -0.5596864   0.27199012  0.26777009  0.33205465 -0.35926641 -0.01550317 -0.12279588 -0.29194673  0.26501445 -0.06257818  0.24854572 -0.32869915  0.04164395]
 [ 0.30510133  0.10743922  0

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
Z = np.random.randint(0,10,(5,5))
print("Before Sorted : ","\n",Z,"\n")

print("After Sorted the nth column : ","\n",Z[Z[:,1].argsort()])

Before Sorted :  
 [[3 5 4 9 4]
 [7 3 6 6 9]
 [2 6 6 0 3]
 [3 8 9 3 1]
 [0 2 1 1 8]] 

After Sorted the nth column :  
 [[0 2 1 1 8]
 [7 3 6 6 9]
 [3 5 4 9 4]
 [2 6 6 0 3]
 [3 8 9 3 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
Z = np.random.randint(0,5,(5,12))

print((~Z.any(axis=0)).any())


False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
Z = np.random.uniform(0,5,10)
z = 1
m = Z.flat[np.abs(Z - z).argmin()]

print(m)

1.299854794213053


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
it = np.nditer([A,B,None])

for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10),"Range_10")
print (Z.name)

Range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))

print(Z)

[3. 1. 5. 2. 2. 2. 4. 3. 3. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)

print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))

print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)

print(sum)

[[67 43 38 58]
 [56 64 53 61]
 [53 65 69 52]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)

D_means = D_sums / D_counts

print(D_means)

[0.42190615 0.5445532  0.50000087 0.65696836 0.55098836 0.56804773 0.41903973 0.68097123 0.54648954 0.5515042 ]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.randint(0,20,(5,5))
B= np.random.randint(0,20,(5,5))

print(np.diag(np.dot(A, B)))

[419 494 590 395 530]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3

Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z

print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))

print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A = np.arange(25).reshape(5,5)
print("Before Swap : ","\n",A,"\n")

A[[0,1]] = A[[1,0]]
print("After Swap : ","\n",A)

Before Swap :  
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

After Swap :  
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))

F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)

print(G)

[( 5, 36) ( 5, 46) ( 7, 23) ( 7, 69) (12, 22) (12, 29) (12, 36) (12, 69) (17, 31) (17, 87) (18, 32) (18, 60) (22, 29) (23, 69) (31, 87) (32, 60) (36, 46) (36, 69) (36, 70) (36, 73) (36, 81) (36, 88) (40, 55) (40, 81) (55, 81) (70, 81) (71, 73) (71, 84) (73, 84) (73, 88)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6,7,8,8,9,9])
A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 2 3 4 4 6 7 8 8 9 9]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(50)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
    
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,20,100)

print('Negating a boolean: ')
print(np.logical_not(Z, out=Z),"\n")

Z = np.random.uniform(-1.0,1.0,10)

print ('Change the sign of float inplace: ')
print(np.negative(Z, out=Z))

Negating a boolean: 
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 

Change the sign of float inplace: 
[-0.90542683  0.60383775  0.87800987  0.78887565 -0.72298832 -0.22194569  0.60753116 -0.67404655  0.52737949 -0.67374172]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 7.40322371  2.57528167  5.15247409  5.23639187  9.93417581  7.05187926 12.04238044  4.77413088  2.72286032  8.05829934]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,5))
P1 = np.random.uniform(-10,10,(10,5))
p = np.random.uniform(-10, 10, (10,5))

print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[14.1147016  20.8685658  28.11524024 21.00815676 18.69234311 18.4239619  20.72478718 11.4791524  13.1711761  15.02611132]
 [12.25023169 19.7272091  20.61911684 15.62912694 10.75197575 18.86358923 17.38784283 18.61619406 14.73854614 12.1706397 ]
 [19.77023404 13.35598585 17.54533711 15.11790072 10.80930178 16.62639976  9.23152784 19.43152889 17.81717223 15.27945314]
 [14.14654433 15.6105142  20.65351568 18.79516158  9.46172292 17.93764078 14.75721735  7.70558987 15.06685976 16.20854282]
 [12.30589251 15.22927585 28.80970712 16.3560418  16.61503718 11.22612016 17.3340918  15.89235557  7.41508782  5.0953004 ]
 [14.75571186 22.50687635 21.85764844 12.14284793 22.28886261 18.01351162 22.68750641 18.67619014 20.56136406 11.79101791]
 [14.69635076 21.7919378  24.32365688 20.23456645 13.39095666 20.70566467 19.65059237 16.85000903 16.33166713 14.33736701]
 [19.96819574 16.30212991 20.20339272 19.69695187 15.38536125 19.41099895 17.04178999  8.97335522 18.4211342  19.53874833]
 [11.83424404 24

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,15,(10,20))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]

print(Z,"\n")
print(R)

[[ 9 11  8  8 13  5 10  3  6  1  8  0 13  1  7  0  6  4  7 12]
 [10  3  5  7 11 13 14  5  5  8  8  4  6  0  1 11 13 11  3 13]
 [11  1  8  0 13  2  3 14  1  1  1 11  9 14  8  9  6 14  0  1]
 [ 3  7  6  5  3  8 12  1  4  4  2  4  8 10  9  4 10 13 11  1]
 [ 0  5 10  0  6  0 13  7 12  1  0  1  6  2  7  5 13  4  5  9]
 [ 7 12  8  1 13  0 13  5  2 11  0  6 13 11  1  7 10  8 12 11]
 [14 14  0  7 11  0  2  1 13  8  7 13  1  4  7  2  8  7  0 10]
 [ 8 10  4 11  7 11 13  7 11  4 13  4  6  9  5 14 14  7  9  6]
 [ 9  1  5 11  8 13  9  5 14 10  4 12  1  8  8  7  3  8 14 14]
 [ 7 14  7 14 13  5  3  4 13 13  8 10  0  8  7  9 11 12  8 14]] 

[[ 0  0  0  0  0]
 [ 0  9 11  8  8]
 [ 0 10  3  5  7]
 [ 0 11  1  8  0]
 [ 0  3  7  6  5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=int)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(Z, 4)

print ('Before stride: ')
print (Z,"\n")
print ('after strides: ')
print(R)

Before stride: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

after strides: 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,2,(5,5))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)

print ("The rank of the matrix is : ",rank)

The rank of the matrix is :  5


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z = np.random.randint(0,10,100)

print (Z)
print('rank:', np.bincount(Z).argmax())

[9 6 8 8 3 7 9 6 7 3 2 1 2 1 1 3 0 7 2 3 8 6 7 9 2 2 0 2 1 9 0 1 1 8 1 1 1 8 2 2 6 1 6 8 0 2 2 1 6 1 3 5 6 3 7 6 6 6 1 0 7 9 1 6 4 4 7 0 2 1 2 5 3 4 2 4 3 5 9 2 6 9 9 3 0 3 7 7 4 8 6 1 5 4 6 0 2 7 6 5]
rank: 1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)

print(C)

[[[[0 2 3]
   [4 3 3]
   [1 0 2]]

  [[2 3 3]
   [3 3 2]
   [0 2 3]]

  [[3 3 0]
   [3 2 1]
   [2 3 0]]

  [[3 0 0]
   [2 1 2]
   [3 0 4]]

  [[0 0 1]
   [1 2 0]
   [0 4 2]]

  [[0 1 1]
   [2 0 3]
   [4 2 2]]

  [[1 1 4]
   [0 3 1]
   [2 2 2]]

  [[1 4 4]
   [3 1 4]
   [2 2 3]]]


 [[[4 3 3]
   [1 0 2]
   [4 4 0]]

  [[3 3 2]
   [0 2 3]
   [4 0 3]]

  [[3 2 1]
   [2 3 0]
   [0 3 0]]

  [[2 1 2]
   [3 0 4]
   [3 0 4]]

  [[1 2 0]
   [0 4 2]
   [0 4 2]]

  [[2 0 3]
   [4 2 2]
   [4 2 4]]

  [[0 3 1]
   [2 2 2]
   [2 4 1]]

  [[3 1 4]
   [2 2 3]
   [4 1 1]]]


 [[[1 0 2]
   [4 4 0]
   [0 2 4]]

  [[0 2 3]
   [4 0 3]
   [2 4 0]]

  [[2 3 0]
   [0 3 0]
   [4 0 4]]

  [[3 0 4]
   [3 0 4]
   [0 4 3]]

  [[0 4 2]
   [0 4 2]
   [4 3 0]]

  [[4 2 2]
   [4 2 4]
   [3 0 0]]

  [[2 2 2]
   [2 4 1]
   [0 0 4]]

  [[2 2 3]
   [4 1 1]
   [0 4 1]]]


 [[[4 4 0]
   [0 2 4]
   [1 0 1]]

  [[4 0 3]
   [2 4 0]
   [0 1 1]]

  [[0 3 0]
   [4 0 4]
   [1 1 3]]

  [[3 0 4]
   [0 4 3]
   [1 3 0]]

  [[0 4 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1 14  7  9  7]
 [14  9 14 12 14]
 [ 7 14  4 42 11]
 [ 9 12 42  6 17]
 [ 7 14 11 17  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 100, 200
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])

print(S)

[[20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:

def iterate(Z):
   
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

print (Z[np.argpartition(-Z,n)[:n]])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.75 s ± 16.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
181 ms ± 10.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
143 ms ± 16.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]

print(Z,"\n")
print(U)

[[1 0 2]
 [0 4 2]
 [4 1 2]
 [4 3 2]
 [3 3 1]
 [3 1 4]
 [4 4 4]
 [3 4 2]
 [1 3 0]
 [3 0 2]] 

[[1 0 2]
 [0 4 2]
 [4 1 2]
 [4 3 2]
 [3 3 1]
 [3 1 4]
 [3 4 2]
 [1 3 0]
 [3 0 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)

print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,4))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(Z,"\n")
print(uZ)

[[1 0 1 0]
 [0 1 1 0]
 [1 1 0 0]
 [0 1 1 0]
 [1 1 0 0]
 [0 0 0 0]] 

[[0 0 0 0]
 [0 1 1 0]
 [1 0 1 0]
 [1 1 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

print(np.einsum('i->', A),"\n" )      
print(np.einsum('i,i->i', A, B),"\n") 
print(np.einsum('i,i', A, B),"\n")    
print(np.einsum('i,j->ij', A, B))

4.5312295447287525 

[0.6336094  0.29841342 0.32888614 0.00132057 0.09309772 0.00107991 0.27673793 0.00374664 0.96811162 0.05708149] 

2.6620848411992464 

[[6.33609400e-01 6.46263457e-01 2.96616512e-01 1.10449618e-01 5.20990614e-01 4.83272139e-02 6.69835554e-01 5.51982940e-02 8.71703343e-01 8.28060446e-02]
 [2.92570385e-01 2.98413421e-01 1.36963257e-01 5.10003282e-02 2.40568439e-01 2.23151860e-02 3.09297883e-01 2.54879207e-02 4.02510731e-01 3.82358538e-02]
 [7.02541303e-01 7.16572025e-01 3.28886141e-01 1.22465700e-01 5.77670445e-01 5.35848487e-02 7.42708587e-01 6.12034502e-02 9.66538063e-01 9.18147149e-02]
 [7.57562957e-03 7.72692537e-03 3.54643857e-03 1.32056973e-03 6.22912459e-03 5.77815087e-04 8.00876064e-03 6.59967841e-04 1.04223542e-02 9.90054629e-04]
 [1.13221984e-01 1.15483183e-01 5.30034905e-02 1.97366467e-02 9.30977202e-02 8.63576679e-03 1.19695368e-01 9.86358524e-03 1.55767862e-01 1.47969153e-02]
 [1.41585263e-02 1.44412916e-02 6.62814136e-03 2.46808810e-03 1.16419663e-02 1.

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

print(r[1:],"\n")
print(r_int,"\n")
print(x_int,"\n")
print(y_int)

[1.00000000e-01 2.00994225e-01 3.03948099e-01 4.09773428e-01 5.19310334e-01 6.33316917e-01 7.52465988e-01 8.77347271e-01 1.00847317e+00 1.14628646e+00 1.29116861e+00 1.44344797e+00 1.60340735e+00 1.77129076e+00 1.94730924e+00 2.13164591e+00 2.32446017e+00 2.52589132e+00 2.73606151e+00 2.95507828e+00 3.18303664e+00 3.42002084e+00 3.66610588e+00 3.92135873e+00 4.18583938e+00 4.45960178e+00 4.74269456e+00 5.03516168e+00 5.33704304e+00 5.64837490e+00 5.96919031e+00 6.29951948e+00 6.63939009e+00 6.98882753e+00 7.34785520e+00 7.71649464e+00 8.09476576e+00 8.48268698e+00 8.88027538e+00 9.28754684e+00 9.70451612e+00 1.01311970e+01 1.05676022e+01 1.10137439e+01 1.14696332e+01 1.19352807e+01 1.24106962e+01 1.28958890e+01 1.33908678e+01 1.38956409e+01 1.44102161e+01 1.49346005e+01 1.54688013e+01 1.60128248e+01 1.65666773e+01 1.71303646e+01 1.77038924e+01 1.82872658e+01 1.88804900e+01 1.94835697e+01 2.00965094e+01 2.07193135e+01 2.13519861e+01 2.19945311e+01 2.26469523e+01 2.33092533e+01 2.3981437

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)

print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) 
N = 1000 

idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [5,95])

print(confint)

[-0.11284214  0.25656943]
